export const enum SyncFlags {
  CREATE = 0,
  INSERT,
  SET_TEXT,
  REMOVE,
  DISPLAY,
  ADD_EVENT,
  UPDATE_PROP,
  SET_MODEL_VALUE,
  DISPATCH_EVENT,
  SELECTOR,
  ADD_INTERSECTION_OBSERVER,
  REMOVE_INTERSECTION_OBSERVER,
  INTERSECTION_OBSERVER_ENTRY
}
